program ServicoFacil;

uses
  Forms,
  Dialogs,
  SysUtils,
  UMenu in 'UMenu.pas' {fMenu},
  DmdDatabase in '..\ssfacil\DmdDatabase.pas' {dmDatabase: TDataModule},
  ACBrUtil in 'C:\ACBr\Fontes\ACBrComum\ACBrUtil.pas',
  uXMLClientDataSet in '..\ssfacil\NFSe\uXMLClientDataSet.pas',
  uXMLClientDataSet_NFSe_CampoBom in '..\ssfacil\NFSe\uXMLClientDataSet_NFSe_CampoBom.pas',
  uXMLNFSe_CampoBom in '..\ssfacil\NFSe\uXMLNFSe_CampoBom.pas',
  SelfPrintDefs in '..\ssfacil\sendmail\SelfPrintDefs.pas',
  SendMail in '..\ssfacil\sendmail\SendMail.pas',
  SendMailOptions in '..\ssfacil\sendmail\SendMailOptions.pas' {FormSendMailOptions},
  nfe_v110 in '..\ssfacil\nfe_v110.pas',
  UBaixaOrdemServico in '..\ssfacil\UBaixaOrdemServico.pas' {frmBaixaOrdemServico},
  UBaixaOrdemServico_Def in '..\ssfacil\UBaixaOrdemServico_Def.pas' {frmBaixaOrdemServico_Def},
  UBaixaOrdemServico_Itens in '..\ssfacil\UBaixaOrdemServico_Itens.pas' {frmBaixaOrdemServico_Itens},
  UBaixaOrdemServico_Mat in '..\ssfacil\UBaixaOrdemServico_Mat.pas' {frmBaixaOrdemServico_Mat},
  UBaixaOrdemServico_Serv in '..\ssfacil\UBaixaOrdemServico_Serv.pas' {frmBaixaOrdemServico_Serv},
  UCadAgenda in '..\ssfacil\UCadAgenda.pas' {frmCadAgenda},
  UCadAgenda_Inf in '..\ssfacil\UCadAgenda_Inf.pas' {frmCadAgenda_Inf},
  UCadBanco in '..\ssfacil\UCadBanco.pas' {frmCadBanco},
  UCadCidade in '..\ssfacil\UCadCidade.pas' {frmCadCidade},
  UCadCNAE in '..\ssfacil\UCadCNAE.pas' {frmCadCNAE},
  UCadCondPgto in '..\ssfacil\UCadCondPgto.pas' {frmCadCondPgto},
  UCadContas in '..\ssfacil\UCadContas.pas' {frmCadContas},
  UCadContrato in '..\ssfacil\UCadContrato.pas' {frmCadContrato},
  UCadContrato_Servico_Int in '..\ssfacil\UCadContrato_Servico_Int.pas' {frmCadContrato_Servico_Int},
  UCadContratoServ in '..\ssfacil\UCadContratoServ.pas' {frmCadContratoServ},
  UCadFilial in '..\ssfacil\uCadFilial.pas' {frmCadFilial},
  uCadFilial_Download in '..\ssfacil\uCadFilial_Download.pas' {frmCadFilial_Download},
  uCadFilial_Email in '..\ssfacil\uCadFilial_Email.pas' {frmCadFilial_Email},
  uCadFilialRelatorios in '..\ssfacil\uCadFilialRelatorios.pas' {frmCadFilialRelatorios},
  uCadFuncionario in '..\ssfacil\uCadFuncionario.pas' {frmCadFuncionario},
  UCadNatureza in '..\ssfacil\UCadNatureza.pas' {frmCadNatureza},
  UCadNotaServico_Canc in '..\ssfacil\UCadNotaServico_Canc.pas' {frmCadNotaServico_Canc},
  UCadNotaServico_Itens in '..\ssfacil\UCadNotaServico_Itens.pas' {frmCadNotaServico_Itens},
  UCadNotaServico_Obs in '..\ssfacil\UCadNotaServico_Obs.pas' {frmCadNotaServico_Obs},
  UCadOrdemServico in '..\ssfacil\UCadOrdemServico.pas' {frmCadOrdemServico},
  UCadOrdemServico_Itens in '..\ssfacil\UCadOrdemServico_Itens.pas' {frmCadOrdemServico_Itens},
  uCadOrdemServico_Param in '..\ssfacil\uCadOrdemServico_Param.pas' {frmCadOrdemServico_Param},
  UCadOS_Simples in '..\ssfacil\uCadOS_Simples.pas' {frmCadOS_Simples},
  UCadOS_Simples_Exec in '..\ssfacil\UCadOS_Simples_Exec.pas' {frmCadOS_Simples_Exec},
  UCadOS_Simples_Item in '..\ssfacil\UCadOS_Simples_Item.pas' {frmCadOS_Simples_Item},
  uCadPessoa in '..\ssfacil\uCadPessoa.pas' {frmCadPessoa},
  UCadPessoa_Servico in '..\ssfacil\UCadPessoa_Servico.pas' {frmCadPessoa_Servico},
  UCadPessoa_Servico_Int in '..\ssfacil\UCadPessoa_Servico_Int.pas' {frmCadPessoa_Servico_Int},
  UCadRecibo in '..\ssfacil\UCadRecibo.pas' {frmCadRecibo},
  UCadRecibo_Itens in '..\ssfacil\UCadRecibo_Itens.pas' {frmCadRecibo_Itens},
  UCadRegime_Trib in '..\ssfacil\UCadRegime_Trib.pas' {frmCadRegime_Trib},
  UCadServico in '..\ssfacil\UCadServico.pas' {frmCadServico},
  UCadServico_Int in '..\ssfacil\UCadServico_Int.pas' {frmCadServico_Int},
  UCadSetor in '..\ssfacil\uCadSetor.pas' {frmCadSetor},
  UCadTab_IBPT in '..\ssfacil\UCadTab_IBPT.pas' {frmCadTab_IBPT},
  UCadTipoCobranca in '..\ssfacil\UCadTipoCobranca.pas' {frmCadTipoCobranca},
  UCadUF in '..\ssfacil\UCadUF.pas' {frmCadUF},
  UConsLimite_Credito in '..\ssfacil\UConsLimite_Credito.pas' {frmConsLimite_Credito},
  UConsNotas_SER in '..\ssfacil\UConsNotas_SER.pas' {frmConsNotas_SER},
  UConsOrdemServico in '..\ssfacil\UConsOrdemServico.pas' {frmConsOrdemServico},
  UConsOrdemServico_Mat in '..\ssfacil\UConsOrdemServico_Mat.pas' {frmConsOrdemServico_Mat},
  UConsOrdemServico_Nota in '..\ssfacil\UConsOrdemServico_Nota.pas' {frmConsOrdemServico_Nota},
  UConsPessoa_Fat in '..\ssfacil\UConsPessoa_Fat.pas' {frmConsPessoa_Fat},
  UConsPessoa_Fin in '..\ssfacil\UConsPessoa_Fin.pas' {frmConsPessoa_Fin},
  UDMCadAgenda in '..\ssfacil\UDMCadAgenda.pas' {DMCadAgenda: TDataModule},
  UDMCadBanco in '..\ssfacil\UDMCadBanco.pas' {DMCadBanco: TDataModule},
  UDMCadCidade in '..\ssfacil\UDMCadCidade.pas' {DMCadCidade: TDataModule},
  UDMCadCNAE in '..\ssfacil\UDMCadCNAE.pas' {DMCadCNAE: TDataModule},
  UDMCadCondPgto in '..\ssfacil\UDMCadCondPgto.pas' {DMCadCondPgto: TDataModule},
  UDMCadConfig_Email in '..\ssfacil\UDMCadConfig_Email.pas' {DMCadConfig_Email: TDataModule},
  UDMCadContabilista in '..\ssfacil\UDMCadContabilista.pas' {DMCadContabilista: TDataModule},
  UDMCadContas in '..\ssfacil\UDMCadContas.pas' {DMCadContas: TDataModule},
  UDMCadFeriado in '..\ssfacil\UDMCadFeriado.pas' {DMCadFeriado: TDataModule},
  UDMCadFeriado_Fixo in '..\ssfacil\UDMCadFeriado_Fixo.pas' {DMCadFeriado_Fixo: TDataModule},
  UDMCadFilial in '..\ssfacil\UDMCadFilial.pas' {DMCadFilial: TDataModule},
  UDMCadFuncionario in '..\ssfacil\UDMCadFuncionario.pas' {DMCadFuncionario: TDataModule},
  UDMCadNatureza in '..\ssfacil\UDMCadNatureza.pas' {DMCadNatureza: TDataModule},
  UDMCadNotaServico in '..\ssfacil\UDMCadNotaServico.pas' {DMCadNotaServico: TDataModule},
  UDMCadOrdemServico in '..\ssfacil\UDMCadOrdemServico.pas' {DMCadOrdemServico: TDataModule},
  UDMCadOS in '..\ssfacil\UDMCadOS.pas' {DMCadOS: TDataModule},
  UDMCadPais in '..\ssfacil\UDMCadPais.pas' {DMCadPais: TDataModule},
  UDMCadPessoa in '..\ssfacil\UDMCadPessoa.pas' {DMCadPessoa: TDataModule},
  UDMCadProvedor in '..\ssfacil\UDMCadProvedor.pas' {DMCadProvedor: TDataModule},
  UDMCadRecibo in '..\ssfacil\UDMCadRecibo.pas' {DMCadRecibo: TDataModule},
  UDMCadRegime_Trib in '..\ssfacil\UDMCadRegime_Trib.pas' {DMCadRegime_Trib: TDataModule},
  UDMCadServico in '..\ssfacil\UDMCadServico.pas' {DMCadServico: TDataModule},
  UDMCadServico_Int in '..\ssfacil\UDMCadServico_Int.pas' {DMCadServico_Int: TDataModule},
  UDMCadTab_IBPT in '..\ssfacil\UDMCadTab_IBPT.pas' {DMCadTab_IBPT: TDataModule},
  UDMCadTipoCobranca in '..\ssfacil\UDMCadTipoCobranca.pas' {DMCadTipoCobranca: TDataModule},
  UDMCadUF in '..\ssfacil\UDMCadUF.pas' {DMCadUF: TDataModule},
  UDMConsLimite_Credito in '..\ssfacil\UDMConsLimite_Credito.pas' {DMConsLimite_Credito: TDataModule},
  UDMConsNotas_SER in '..\ssfacil\UDMConsNotas_SER.pas' {DMConsNotas_SER: TDataModule},
  UDMConsPessoa in '..\ssfacil\UDMConsPessoa.pas' {DMConsPessoa: TDataModule},
  UDMGravarFinanceiro in '..\ssfacil\UDMGravarFinanceiro.pas' {DMGravarFinanceiro: TDataModule},
  UDMMovimento in '..\ssfacil\UDMMovimento.pas' {DMMovimento: TDataModule},
  UDMNFe in '..\ssfacil\UDMNFe.pas' {DMNFe: TDataModule},
  UDMRel in '..\ssfacil\UDMRel.pas' {DMRel: TDataModule},
  UDMUtil in '..\ssfacil\UDMUtil.pas' {DMUtil: TDataModule},
  UEscolhe_Filial in '..\ssfacil\UEscolhe_Filial.pas' {frmEscolhe_Filial},
  uFrmSobre in '..\ssfacil\uFrmSobre.pas' {frmSobre},
  UGerar_NFSe in '..\ssfacil\UGerar_NFSe.pas' {frmGerar_NFSe},
  UNFe_ConsultaCadastro in '..\ssfacil\UNFe_ConsultaCadastro.pas' {fNFe_ConsultaCadastro},
  uNFeComandos in '..\ssfacil\uNFeComandos.pas',
  URelDanfe_NFSe in '..\ssfacil\URelDANFE_NFSe.pas' {fRelDANFE_NFSe},
  URelDanfe_NFSe_SL in '..\ssfacil\URelDANFE_NFSe_SL.pas' {fRelDANFE_NFSe_SL},
  URelNotas_SER in '..\ssfacil\URelNotas_SER.pas' {fRelNotas_SER},
  URelOrdemServico in '..\ssfacil\URelOrdemServico.pas' {fRelOrdemServico},
  uRelOSSimples in '..\ssfacil\uRelOSSimples.pas' {fRelOSSimples},
  uRelOSSimplesB in '..\ssfacil\uRelOSSimplesB.pas' {fRelOSSimplesB},
  URelPessoa in '..\ssfacil\URelPessoa.pas' {fRelPessoa},
  URelRecibo in '..\ssfacil\URelRecibo.pas' {fRelRecibo},
  USel_Pessoa in '..\ssfacil\USel_Pessoa.pas' {frmSel_Pessoa},
  uUtilCliente in '..\ssfacil\uUtilCliente.pas',
  uUtilPadrao in '..\ssfacil\uUtilPadrao.pas',
  UCadPais in '..\ssfacil\UCadPais.pas' {frmCadPais},
  rsDBUtils in '..\rslib\nova\rsDBUtils.pas',
  LogProvider in '..\logs\src\LogProvider.pas',
  LogTypes in '..\logs\src\LogTypes.pas',
  USel_ContaOrc in '..\ssfacil\USel_ContaOrc.pas' {frmSel_ContaOrc},
  UDMCob_Eletronica in '..\ssfacil\UDMCob_Eletronica.pas' {DMCob_Eletronica: TDataModule},
  uRelBoletoBanrisul in '..\ssfacil\uRelBoletoBanrisul.pas' {fRelBoletoBanrisul},
  UCadProvedor in '..\ssfacil\UCadProvedor.pas' {frmCadProvedor},
  UDMCadExtComissao in '..\ssfacil\UDMCadExtComissao.pas' {DMCadExtComissao: TDataModule},
  UConsFat_Mensal in '..\ssfacil\UConsFat_Mensal.pas' {frmConsFat_Mensal},
  UDMConsFat_Mensal in '..\ssfacil\UDMConsFat_Mensal.pas' {DMConsFat_Mensal: TDataModule},
  UCadObs_Aux in '..\ssfacil\UCadObs_Aux.pas' {frmCadObs_Aux},
  UDMCadObs_Aux in '..\ssfacil\UDMCadObs_Aux.pas' {DMCadObs_Aux: TDataModule},
  uUtilCobranca in '..\ssfacil\uUtilCobranca.pas',
  uCobRemessa in '..\ssfacil\cobranca\uCobRemessa.pas' {fCobRemessa},
  uCobRetorno in '..\ssfacil\cobranca\uCobRetorno.pas' {fCobRetorno},
  URelRemessa in '..\ssfacil\URelRemessa.pas' {fRelRemessa},
  UDMCadSetor in '..\ssfacil\UDMCadSetor.pas' {DmCadSetor: TDataModule},
  UCadAtividade_Cid in '..\ssfacil\UCadAtividade_Cid.pas' {frmCadAtividade_Cid},
  UDMCadAtividade_Cid in '..\ssfacil\UDMCadAtividade_Cid.pas' {DMCadAtividade_Cid: TDataModule},
  URelNotas_ES in '..\ssfacil\URelNotas_ES.pas' {fRelNotas_ES},
  UDMConsNotas_ES in '..\ssfacil\UDMConsNotas_ES.pas' {DMConsNotas_ES: TDataModule},
  UHistServico_Prod in '..\ssfacil\UHistServico_Prod.pas' {frmHistServico_Prod},
  USel_Produto in '..\ssfacil\USel_Produto.pas' {frmSel_Produto},
  UCadFeriado in '..\ssfacil\UCadFeriado.pas' {frmCadFeriado},
  UCadFeriado_Dig in '..\ssfacil\UCadFeriado_Dig.pas' {frmCadFeriado_Dig},
  UCadFeriado_Fixo in '..\ssfacil\UCadFeriado_Fixo.pas' {frmCadFeriado_Fixo},
  URelContrato_Det in '..\ssfacil\URelContrato_Det.pas' {fRelContrato_Det},
  UCadContabilista in '..\ssfacil\uCadContabilista.pas' {frmCadContabilista},
  UCadConfig_Email in '..\ssfacil\UCadConfig_Email.pas' {frmCadConfig_Email},
  DmdDatabase_NFeBD in '..\ssfacil\DmdDatabase_NFeBD.pas' {dmDatabase_NFeBD: TDataModule},
  UDMCadDuplicata in '..\ssfacil\UDMCadDuplicata.pas' {DMCadDuplicata: TDataModule},
  UGerar_NFSe_txt in 'UGerar_NFSe_txt.pas' {frmGerar_NFSe_txt},
  UDMGerar_NFSe in 'UDMGerar_NFSe.pas' {DMGerar_NFSe: TDataModule},
  UImp_Cliente_Txt in 'UImp_Cliente_Txt.pas' {frmImp_Cliente_Txt},
  URelTesteNossoNumero in '..\ssfacil\URelTesteNossoNumero.pas' {fRelTesteNossoNumero},
  URelDanfe_NFSe_CB in '..\ssfacil\URelDANFE_NFSe_CB.pas' {fRelDanfe_NFSe_CB},
  UCadContrato_Material in '..\ssfacil\UCadContrato_Material.pas' {frmCadContratoMaterial},
  uXMLClientDataSet_NFSe_PortoAlegre in '..\ssfacil\NFSe\uXMLClientDataSet_NFSe_PortoAlegre.pas',
  URelDanfe_NFSe_Poa in '..\ssfacil\URelDANFE_NFSe_Poa.pas' {fRelDanfe_NFSe_Poa},
  uUtilTabela in '..\ssfacil\uUtilTabela.pas',
  uXMLNFSe_PortoAlegre in '..\ssfacil\NFSe\uXMLNFSe_PortoAlegre.pas',
  UConsPessoa_Fat_Itens in '..\ssfacil\UConsPessoa_Fat_Itens.pas' {frmConsPessoa_Fat_Itens},
  UConsPessoa_Prod in '..\ssfacil\UConsPessoa_Prod.pas' {frmConsPessoa_Prod},
  USel_EnqIPI in '..\ssfacil\USel_EnqIPI.pas' {frmSel_EnqIPI},
  USel_OS_Servico in '..\ssfacil\USel_OS_Servico.pas' {frmSel_OS_Servico},
  UDMCadOS_TAux in '..\ssfacil\UDMCadOS_TAux.pas' {DMCadOS_TAux: TDataModule},
  uGerar_NFSe_Consumo in '..\ssfacil\uGerar_NFSe_Consumo.pas' {frmGerar_NFSe_Consumo},
  URelOrdemServico2 in '..\ssfacil\URelOrdemServico2.pas' {fRelOrdemServico2},
  uCadOS_Motor in '..\ssfacil\uCadOS_Motor.pas' {frmCadOS_Motor},
  uCadOS_Acionamento in '..\ssfacil\uCadOS_Acionamento.pas' {frmCadOs_Acionamento},
  uCadOS_Transformador in '..\ssfacil\uCadOS_Transformador.pas' {frmCadOS_Transformador},
  USel_Servico_Extra in '..\ssfacil\USel_Servico_Extra.pas' {frmSel_Servico_Extra},
  USenha in '..\ssfacil\USenha.pas' {frmSenha},
  UEnviaEmailTitulos in '..\ssfacil\UEnviaEmailTitulos.pas' {frmEnviaEmailTitulos},
  USel_OS_Servico2 in '..\ssfacil\USel_OS_Servico2.pas' {frmSel_OS_Servico2},
  USel_Atividade in '..\ssfacil\USel_Atividade.pas' {frmSel_Atividade},
  USel_Processo in '..\ssfacil\USel_Processo.pas' {frmSel_Processo},
  UCob_Remessa_Alt in '..\ssfacil\cobranca\UCob_Remessa_Alt.pas' {frmCobRemessa_Alt},
  UCob_Remessa_Alt_All in '..\ssfacil\cobranca\UCob_Remessa_Alt_All.pas' {frmCobAlteraCarteira},
  USel_Ped_Servico in '..\ssfacil\USel_Ped_Servico.pas' {frmSel_Ped_Servico},
  UConsNotaServico_NFeBD in '..\ssfacil\UConsNotaServico_NFeBD.pas' {frmConsNotaServico_NFeBD},
  UCadSetor_Proc in '..\ssfacil\UCadSetor_Proc.pas' {frmCadSetor_Proc},
  UDMImportarXML_NFSe in '..\ssfacil\importarxmlnfe\UDMImportarXML_NFSe.pas' {DMImportarXML_NFSe: TDataModule},
  uImportarXML_NFSe in '..\ssfacil\importarxmlnfe\UImportarXML_NFSe.pas' {frmImportarXML_NFSe},
  UDMSel_Produto in '..\ssfacil\UDMSel_Produto.pas' {DMSel_Produto: TDataModule},
  USel_Produto_Preco in '..\ssfacil\USel_Produto_Preco.pas' {frmSel_Produto_Preco},
  USel_Produto_Lote in '..\ssfacil\PedidoLoja\USel_Produto_Lote.pas' {frmSel_Produto_Lote},
  USel_Titulos in '..\ssfacil\USel_Titulos.pas' {frmSel_Titulos},
  uConsAgenda in '..\ssfacil\uConsAgenda.pas' {frmConsAgenda},
  uGrava_Erro in '..\ssfacil\uGrava_Erro.pas',
  udmNFSe in 'EnvioAcbr\udmNFSe.pas' {dmNFSe: TDataModule},
  UCadFilial_Certificado in 'UCadFilial_Certificado.pas' {frmCadFilial_Certificado},
  UDMCadFilial_Certificado in 'UDMCadFilial_Certificado.pas' {DMFilial_Certificado: TDataModule},
  UCadTipoCobranca_Itens in '..\ssfacil\UCadTipoCobranca_Itens.pas' {frmCadTipoCobranca_Itens},
  UCadNotaServico_acbr in 'UCadNotaServico_acbr.pas' {frmCadNotaServico_acbr},
  classe.CalcularPeso in '..\ssfacil\Classes\classe.CalcularPeso.pas',
  classe.ConexaoBD in '..\ssfacil\Classes\classe.ConexaoBD.pas',
  classe.Controle in '..\ssfacil\Classes\classe.Controle.pas',
  classe.ControlePedidoProjeto in '..\ssfacil\Classes\classe.ControlePedidoProjeto.pas',
  Classe.DataSetToExcel in '..\ssfacil\Classes\Classe.DataSetToExcel.pas',
  classe.Gravar.Estoque in '..\ssfacil\Classes\classe.Gravar.Estoque.pas',
  classe.Gravar.Movimento in '..\ssfacil\Classes\classe.Gravar.Movimento.pas',
  classe.validaemail in '..\ssfacil\Classes\classe.validaemail.pas',
  uDadosEmail in '..\ssfacil\Classes\uDadosEmail.pas',
  uPessoa in '..\ssfacil\Classes\uPessoa.pas',
  UVendedor_Config in '..\ssfacil\UVendedor_Config.pas' {frmVendedor_Config},
  UCadPessoa_ProdICMS in '..\ssfacil\UCadPessoa_ProdICMS.pas' {frmCadPessoa_ProdICMS},
  USel_CBenef in '..\ssfacil\USel_CBenef.pas' {frmSel_CBenef},
  UDMLiberacao_Cob in '..\ssfacil\UDMLiberacao_Cob.pas' {DMLiberacao_Cob: TDataModule},
  USenha_Nova in '..\ssfacil\USenha_Nova.pas' {frmSenha_Nova},
  uUtilForm in '..\ssfacil\uUtilForm.pas',
  USel_OBS_Aux in '..\ssfacil\USel_OBS_Aux.pas' {frmSel_OBS_Aux},
  USel_CentroCusto in '..\ssfacil\USel_CentroCusto.pas' {frmSel_CentroCusto},
  UDMSelOS_Projeto in '..\ssfacil\UDMSelOS_Projeto.pas' {DMSelOS_Projeto: TDataModule},
  USel_OS_Projeto in '..\ssfacil\USel_OS_Projeto.pas' {frmSel_OS_Projeto},
  uUtilServico in '..\ssfacil\uUtilServico.pas',
  uCadArqModeloContrato in '..\ssfacil\uCadArqModeloContrato.pas' {frmCadArqModeloContrato},
  uCadOrdemServico_VlrServico in '..\ssfacil\uCadOrdemServico_VlrServico.pas' {frmCadOrdemServico_VlrServico},
  uSel_Filial_Servidor in '..\ssfacil\uSel_Filial_Servidor.pas' {frmSel_Filial_Servidor},
  UDMLiberacao in '..\ssfacil\UDMLiberacao.pas' {DMLiberacao: TDataModule},
  USel_Bandeira_Ope in '..\ssfacil\USel_Bandeira_Ope.pas' {frmSel_Bandeira_Ope},
  uUtilImpressao in '..\ssfacil\uUtilImpressao.pas',
  uNFeConsts in '..\ssfacil\uNFeConsts.pas',
  UDMEtiqueta in '..\ssfacil\UDMEtiqueta.pas' {DMEtiqueta: TDataModule},
  USel_Plano_Contabil in '..\ssfacil\USel_Plano_Contabil.pas' {frmSel_Plano_Contabil},
  classe.NFSe.Resultado in '..\SSNFSe\Classes\classe.NFSe.Resultado.pas',
  UCancelaDup in '..\ssfacil\UCancelaDup.pas' {frmCancelaDup},
  UImporta_Contrato_Sunny in '..\ssfacil\excel\UImporta_Contrato_Sunny.pas' {frmImporta_Contrato_Sunny},
  UCadNotaServico in 'UCadNotaServico.pas' {frmCadNotaServico},
  uCadOrdemServico_Parc in '..\ssfacil\uCadOrdemServico_Parc.pas' {frmCadOrdemServico_Parc},
  uCadOrdemServico_VlrEntrada in '..\ssfacil\uCadOrdemServico_VlrEntrada.pas' {frmCadOrdemServico_VlrEntrada},
  uGrava_OrdemServico in '..\ssfacil\uGrava_OrdemServico.pas',
  UCadOS_Simples_Mat in '..\ssfacil\UCadOS_Simples_Mat.pas' {frmCadOS_Simples_Mat},
  uCadOS_Simples_Pagto in '..\ssfacil\UCadOS_Simples_Pagto.pas' {frmCadOS_Simples_Pagto},
  uCadRaca in '..\ssfacil\Pet\uCadRaca.pas' {frmCadRaca},
  UDMCadRaca in '..\ssfacil\Pet\UDMCadRaca.pas' {DMCadRaca: TDataModule},
  uCadTipo_Animal in '..\ssfacil\Pet\uCadTipo_Animal.pas' {frmCadTipo_Animal},
  UDMCadTipo_Animal in '..\ssfacil\Pet\UDMCadTipo_Animal.pas' {DMCadTipo_Animal: TDataModule},
  UCadCor in '..\ssfacil\UCadCor.pas' {frmCadCor},
  UDMCadCor in '..\ssfacil\UDMCadCor.pas' {DMCadCor: TDataModule},
  UCadFilial_Servico in '..\ssfacil\UCadFilial_Servico.pas' {frmCadFilial_Servico},
  USel_ClasIPI in '..\ssfacil\USel_ClasIPI.pas' {frmSel_ClasIPI},
  uVelocidadeCorte in '..\ssfacil\Classes\uVelocidadeCorte.pas',
  UNomeProduto in '..\ssfacil\Classes\UNomeProduto.pas';

{$R *.res}

begin
  try
    Application.Initialize;
    Application.Title := 'ServicoFacil';
  //frmAbertura.Show;
   // frmAbertura.Refresh;
   // frmAbertura.Hide;
    //frmAbertura.Free;

    Application.CreateForm(TdmDatabase, dmDatabase);
  Application.CreateForm(TDMUtil, DMUtil);
  Application.CreateForm(TfMenu, fMenu);
  Application.Run;
  except
    on e: Exception do
      ShowMessage('Ocorreu o seguinte erro ao executar: ' + #13 + e.Message);
  end;
end.
